import type { Metadata } from "next";
import Header from "@/components/layout/header";
import { Geist, Geist_Mono } from "next/font/google";
import { getBlogSetting } from "@/lib/api";

import "./globals.css";
import Footer from "@/components/layout/footer";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const setting = await getBlogSetting();
  const title = setting?.nav_bar?.website_information?.title || "Mou1ght";
  return {
    title: {
      template: `${title} | %s`,
      default: `${title} | 首页`,
    },
    description: "Generated by Mou1ght",
    icons: {
      icon: setting?.nav_bar?.website_information?.icon || "/favicon.ico",
    }
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setting = await getBlogSetting();
  const links = setting?.nav_bar?.links || [];
  const title = setting?.nav_bar?.website_information?.title || "Mou1ght";

  return (
    <html lang="en">
      <head>
        <link
          rel="alternate"
          type="application/rss+xml"
          title={`${title} RSS`}
          href="/rss.xml"
        />
        {/* 首帧前应用暗色模式，避免闪烁 */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('mou1ght-theme');var d=t?t==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;if(d)document.documentElement.classList.add('dark')}catch(e){}})();`,
          }}
        />
      </head>
      <body
        className ={cn("antialiased ",geistSans.variable,geistMono.variable)}
      >
        <Header links={links} />
        <main className="w-full min-h-[calc(100vh-4rem)]">
          {children}
        </main>
        <Footer extra={setting?.bottom_extra} />
      </body>
    </html>
  );
}
