import type { Metadata } from "next";
import Header from "@/components/layout/header";
import { Geist, Geist_Mono } from "next/font/google";
import { getBlogSetting } from "@/lib/api";

import "./globals.css";
import Footer from "@/components/layout/footer";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const setting = await getBlogSetting();
  const title = setting?.nav_bar?.website_information?.title || "Mou1ght";
  return {
    title: {
      template: `${title} | %s`,
      default: `${title} | 首页`,
    },
    description: "Generated by Mou1ght",
    icons: {
      icon: setting?.nav_bar?.website_information?.icon || "/favicon.ico",
    }
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setting = await getBlogSetting();
  const links = setting?.nav_bar?.links || [];

  return (
    <html lang="en">
      <body
        className ={cn("antialiased ",geistSans.variable,geistMono.variable)}
      >
        <Header links={links} />
        <main className="w-full">
          {children}
        </main>
        <Footer extra={setting?.bottom_extra} />
      </body>
    </html>
  );
}
